name: Сообщить об ошибке в Salvor DEEP
description: Сообщите о проблеме в русификаторе Salvor DEEP
title: "[Salvor DEEP] "
body:
  - type: dropdown
    id: loader-version
    attributes:
      label: Версия русификатора
      options:
        - "1.0.12"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Описание
      placeholder: Опишите, что произошло и как воспроизвести ошибку.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Скриншот
      description: При необходимости перетащите сюда изображение.
    validations:
      required: false
